import {
  Activity,
  AlertTriangle,
  Bone,
  Bug,
  Brain,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ClipboardList,
  Download,
  Droplet,
  Eye,
  EyeOff,
  FileText,
  FlaskConical,
  Folder,
  Hand,
  HeartPulse,
  LoaderCircle,
  Lock,
  MessageCircle,
  NotebookPen,
  Pill,
  Plus,
  Send,
  Settings,
  Shield,
  Sparkles,
  Thermometer,
  Timer,
  UserRound,
  Utensils,
  Wind,
  X,
  type LucideIcon,
} from "lucide-react";
import type { NavKey } from "../dashboard-model";

export const navIcons: Record<NavKey, LucideIcon> = {
  body: UserRound,
  labs: Droplet,
  symptoms: ClipboardList,
  activity: Activity,
  medications: Pill,
  fasting: Timer,
  breathing: Wind,
  plan: MessageCircle,
  research: Sparkles,
  documents: Folder,
  settings: Settings,
  developer: Bug,
};

export const organIcons: Record<string, LucideIcon> = {
  brain: Brain,
  thyroid: Thermometer,
  lungs: Wind,
  heart: HeartPulse,
  liver: Activity,
  spleen: Shield,
  stomach: Utensils,
  pancreas: Droplet,
  kidneys: Droplet,
  intestines: Activity,
  bladder: Droplet,
  blood: FlaskConical,
  bones: Bone,
  skin: Hand,
  reproductive: UserRound,
};

export {
  Activity,
  AlertTriangle,
  Bug,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Download,
  Eye,
  EyeOff,
  FileText,
  Folder,
  LoaderCircle,
  Lock,
  NotebookPen,
  Pill,
  Plus,
  Send,
  Sparkles,
  Timer,
  Wind,
  X,
};
